
### Raw Events Samples

In this section, you will find examples of raw logs as generated natively by the source. These examples are provided to help integrators understand the data format before ingestion into Sekoia.io. It is crucial for setting up the correct parsing stages and ensuring that all relevant information is captured.


=== "AUTH_CONNECTION_disconnected"

    ```
	Disconnected from user root 1.2.3.4 port 33398
    ```



=== "AUTH_CONNECTION_event"

    ```
	 Connection closed by authenticating user root 1.2.3.4 port 60292 [preauth]
    ```



=== "AUTH_CONNECTION_recieved_disconnect"

    ```
	Received disconnect from 1.2.3.4 port 33398:11: disconnected by user
    ```



=== "AUTH_PUBLIC_KEY"

    ```
	Accepted publickey for root from 1.2.3.4 port 33398 ssh2: RSA SHA256:qzkqJPyBUdiJUC4i/wbJzkYLTcUWwXRArUT90bUw2E0
    ```



=== "AUTH_SESSION_change_user"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxcli-76-ecbf] Event 975279 : User root@127.0.0.1 logged in as pyvmomi
    ```



=== "AUTH_SESSION_change_user_with_user_agent"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxcli-76-ecbf] Event 975279 : User root@127.0.0.1 logged in as pyvmomi Python/3.8.13 (VMkernel; 7.0.3; x86_64)
    ```



=== "AUTH_SESSION_closed"

    ```
	pam_unix(sshd:session): session closed for user root
    ```



=== "AUTH_SESSION_opened"

    ```
	pam_unix(sshd:session): session opened for user root by (uid=0)
    ```



=== "AUTH_SESSION_user"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc opID=esxcli-a5-20ae] [Auth]: User root
    ```



=== "AUTH_SSH_PASSWORD"

    ```
	info hostd[2099656] [Originator@6876 sub=Default opID=esxcli-76-ecbf] Accepted password for user root from 127.0.0.1
    ```



=== "AUTH_SSH_event_closed"

    ```
	 [GenericCorrelator] 3087878379676us: [vob.user.ssh.session.closed] SSH session was closed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_event_opened"

    ```
	   [GenericCorrelator] 3087878318715us: [vob.user.ssh.session.opened] SSH session was opened for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_login_failed"

    ```
	vobd: [GenericCorrelator] 2216526905us: [vob.user.ssh.session.failed] SSH login has failed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_process_closed"

    ```
	   error hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 974676 : SSH session was closed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_process_opened"

    ```
	info hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 974676 : SSH session was opened for 'root@1.2.3.4'.
    ```



=== "NETWORK_HOSTNAME"

    ```
	 DHCPDISCOVER on vmk1 to 255.255.255.255 port 67 interval 1
    ```



=== "NETWORK_SOURCE"

    ```
	Connection from 1.2.3.4 port 33398
    ```



=== "PROCESS_CMD"

    ```
	Executing 'vsanmgmtd -s -c /etc/vmware/vsan/vsanmgmt-config.xml'
    ```



=== "PROCESS_CMD_user"

    ```
	USER root pid 9919303 cmd /bin/hostd-probe.sh ++group=host/vim/vmvisor/hostd-probe/stats/sh
    ```



=== "PROCESS_CMD_user_1"

    ```
	User 'root' running command 'USER=vpxuser python ++group=host/vim/vmvisor/ntnx /get_one_time_password.py'
    ```



=== "PROCESS_LOG_LAUNCHING"

    ```
	healthd: info healthd[2100572] [Originator@6876 sub=PluginLauncher] Launching binary: /usr/lib/vmware/healthd/plugins/bin/ssdStorage.py ++group=healthd-plugins,mem=40 -u http://localhost:9996
    ```



=== "SSHD_ERROR_INVALID_USER"

    ```
	sshd[2102293]: Invalid user administrator from 1.2.3.4 port 41100
    ```



=== "SSHD_MESSAGE_DISCONNECTED"

    ```
	sshd[2102280]: Disconnected from authenticating user root 1.2.3.4 port 21289 [preauth]
    ```



=== "VARIOUS_DEVICE_OUTCOME_REASON"

    ```
	error fdm[7599783] [Originator@6876 sub=Cluster opID=SWI-3cc8cdca] stat(/vmfs/volumes/aaaaaaaa-bbbbbbbb/.vSphere-HA/FDM-ffffffff-1111-4444-5555-666666666666-7-9999999-lnpvcr02) failed with Permission denied
    ```



=== "VARIOUS_FILE_ACTION"

    ```
	Unlocked esx.conf
    ```



=== "VARIOUS_FILE_ACTION_1"

    ```
	 Event [1201736] [2-3]  (fileName = "ds:///vmfs/volumes/63985d53-c3598817-6688-5c6f69e18ad0/HDD01-835/HDD01-835.vmdk", datastore = 'vim.Datastore:d6543eda-9347-4b38-b803-6f5048248ea8:datastore-2809', backingObjectId = "", diskMode = "independent_nonpersistent", split = <unset>, writeThrough = <unset>, thinProvisioned = false, eagerlyScrub = false, uuid = "6000C299-dd5c-07cb-b868-3600b53d2781", contentId = "5c1d0d8547e8b15283e287f5cb18ef5e", changeId = <unset>, parent = null, deltaDiskFormat = <unset>, digestEnabled = false, deltaGrainSize = <unset>, deltaDiskFormatVariant = <unset>, sharing = <unset>, keyId = null, cryptoIntegrityProtectionType = <unset>), deltaDiskFormat = "seSparseFormat", digestEnabled = false, deltaGrainSize = 4, deltaDiskFormatVariant = <unset>, sharing = "sharingNone", keyId = null, cryptoIntegrityProtectionType = <unset>), connectable = null, slotInfo = null, controllerKey = 1000, unitNumber = 3, numaNode = <unset>, capacityInKB = 104857600, capacityInBytes = 107374182400, shar
    ```



=== "VARIOUS_KEY_ACTION"

    ```
	Using key ID  527683eb-be00-ae48-b12d-06e5cffe4c7e to encrypt
    ```



=== "VARIOUS_REASON_1"

    ```
	  [iscsiCorrelator] 3087813295957us: [vob.iscsi.connection.stopped] iScsi connection 0 stopped for vmhba64:C0:T3
    ```



=== "VARIOUS_REASON_10"

    ```
	  info fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1b24a1a7] Unset _accessible for datastore (/vmfs/volumes/aaaaaaaa-bbbbbbbb)
    ```



=== "VARIOUS_REASON_2"

    ```
	 connection 4:0 (iqn.2010-06.com.nutanix:iscsi-dump-c086c177-a1f4-48be-a3b2-b5f2b6517fa6 if=default addr=1.2.3.4:3260 (TPGT:1 ISID:0x1)  (T3 C0)) has recovered (2 attempts)
    ```



=== "VARIOUS_REASON_3"

    ```
	 info hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=233816e0 user=vpxuser] Event 974626 : User vpxuser@10.79.50.22 logged out (login time: Tuesday, 18 April, 2023 07:14:36 AM, number of API invocations: 3, user agent: pyvmomi)
    ```



=== "VARIOUS_REASON_4"

    ```
	 info rhttpproxy[2102807] [Originator@6876 sub=IO.Connection] Failed to shutdown socket; <io_obj p:0x000000f7c12bd0a8, h:23, <TCP '5.6.7.8 : 443'>, <TCP '1.2.3.4 : 39664'>>, e: 104(shutdown: Connection reset by peer)
    ```



=== "VARIOUS_REASON_5"

    ```
	  verbose rhttpproxy[2099165] [Originator@6876 sub=Proxy Req 06028] Connected to localhost:8307 (/sdk) over <io_obj p:0x000000f7c12be288, h:24, <TCP '127.0.0.1 : 29013'>, <TCP '127.0.0.1 : 8307'>>
    ```



=== "VARIOUS_REASON_6"

    ```
	  error kmxa[2098475] [Originator@6876 sub=Libs opID=InitCache-52a74d0e-554c-1fc3-1b1f-bd3c439fd0a3-0] Trust Authority Components not configured.
    ```



=== "VARIOUS_REASON_7"

    ```
	 verbose fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1361339f] Healthstatus of VM /vmfs/volumes/0ced57f7-f5da65c8/ntpnim02/ntpnim02.vmx on live hostId host-103 : true
    ```



=== "VARIOUS_REASON_8"

    ```
	 info hostd[2099655] [Originator@6876 sub=Libs opID=2338d373 user=vpxuser] NetstackInstanceImpl: congestion control algorithm: newreno
    ```



=== "VARIOUS_REASON_9"

    ```
	info fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1b24a1a7] Unset _accessible for datastore (/vmfs/volumes/aaaaaaaa-bbbbbbbb)
    ```



=== "VARIOUS_SERIAL_NUMBER_1"

    ```
	 QuerySerialNumber --- real serial number is 1111222233334444
    ```



=== "VARIOUS_SERIAL_NUMBER_2"

    ```
	 get_serial_num_of_SATA_SAS_disk---serial num is 1111222233334444
    ```



