
### Raw Events Samples

In this section, you will find examples of raw logs as generated natively by the source. These examples are provided to help integrators understand the data format before ingestion into Sekoia.io. It is crucial for setting up the correct parsing stages and ensuring that all relevant information is captured.


=== "AUTH_CONNECTION_disconnected"

    ```
	Disconnected from user root 1.2.3.4 port 33398
    ```



=== "AUTH_CONNECTION_event"

    ```
	 Connection closed by authenticating user root 1.2.3.4 port 60292 [preauth]
    ```



=== "AUTH_CONNECTION_recieved_disconnect"

    ```
	Received disconnect from 1.2.3.4 port 33398:11: disconnected by user
    ```



=== "AUTH_PUBLIC_KEY"

    ```
	Accepted publickey for root from 1.2.3.4 port 33398 ssh2: RSA SHA256:qzkqJPyBUdiJUC4i/wbJzkYLTcUWwXRArUT90bUw2E0
    ```



=== "AUTH_SESSION_change_user"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxcli-76-ecbf] Event 975279 : User root@127.0.0.1 logged in as pyvmomi
    ```



=== "AUTH_SESSION_change_user_with_user_agent"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxcli-76-ecbf] Event 975279 : User root@127.0.0.1 logged in as pyvmomi Python/3.8.13 (VMkernel; 7.0.3; x86_64)
    ```



=== "AUTH_SESSION_closed"

    ```
	pam_unix(sshd:session): session closed for user root
    ```



=== "AUTH_SESSION_opened"

    ```
	pam_unix(sshd:session): session opened for user root by (uid=0)
    ```



=== "AUTH_SESSION_user"

    ```
	info hostd[2099656] [Originator@6876 sub=Vimsvc opID=esxcli-a5-20ae] [Auth]: User root
    ```



=== "AUTH_SSH_PASSWORD"

    ```
	info hostd[2099656] [Originator@6876 sub=Default opID=esxcli-76-ecbf] Accepted password for user root from 127.0.0.1
    ```



=== "AUTH_SSH_event_closed"

    ```
	 [GenericCorrelator] 3087878379676us: [vob.user.ssh.session.closed] SSH session was closed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_event_opened"

    ```
	   [GenericCorrelator] 3087878318715us: [vob.user.ssh.session.opened] SSH session was opened for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_login_failed"

    ```
	vobd: [GenericCorrelator] 2216526905us: [vob.user.ssh.session.failed] SSH login has failed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_process_closed"

    ```
	   error hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 974676 : SSH session was closed for 'root@1.2.3.4'.
    ```



=== "AUTH_SSH_process_opened"

    ```
	info hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 974676 : SSH session was opened for 'root@1.2.3.4'.
    ```



=== "DIFFERENT_EVENTS_1"

    ```
	[Originator@6876 sub=Default] Processing file: /etc/vmware/rhttpproxy/endpoints.conf.d//ccp-endpoints.conf
    ```



=== "DIFFERENT_EVENTS_10"

    ```
	[Originator@6876 sub=IO.Connection] Attempting connection; <resolver p:0x000000cb75848b30, 'localhost:9096', next:(null)>, last e: 111(Connection refused)
    ```



=== "DIFFERENT_EVENTS_11"

    ```
	[Originator@6876 sub=IO.Connection] Attempting connection; <resolver p:0x000000cb75848b30, 'localhost:9096', next:<TCP '127.0.0.1 : 9096'>>, last e: 0(Success)
    ```



=== "DIFFERENT_EVENTS_12"

    ```
	[Originator@6876 sub=IO.Connection] Failed to connect; <io_obj p:0x000000cb7579a9a8, h:34, <TCP '127.0.0.1 : 55911'>, <TCP '127.0.0.1 : 9096'>>, e: 111(Connection refused), duration: 0msec
    ```



=== "DIFFERENT_EVENTS_13"

    ```
	[Originator@6876 sub=IO.Connection] Failed to read buffer from stream; SSL(<io_obj p:0x000000cbb90980e8, h:23, <TCP '1.2.3.4 : 443'>, <TCP '3.4.5.6 : 58293'>>) e: 104(Connection reset by peer), async: true, duration: 1882msec
    ```



=== "DIFFERENT_EVENTS_14"

    ```
	[Originator@6876 sub=IO.Connection] Failed to shutdown socket; <io_obj p:0x000000cb7579a9a8, h:34, <TCP '127.0.0.1 : 55911'>, <TCP '127.0.0.1 : 9096'>>, e: 104(shutdown: Connection reset by peer)
    ```



=== "DIFFERENT_EVENTS_15"

    ```
	[Originator@6876 sub=Internalsvc.HostsvcManager opID=ef773311 sid=52f14cc5 user=testUser:testDomain] Start refresh VSAN datastore in Hostd
    ```



=== "DIFFERENT_EVENTS_16"

    ```
	[Originator@6876 sub=Libs opID=11807a55-a5-3dd1 sid=5290a04a user=testUser:DOMAIN_START
    pxd-extension-UUIDTEST] New error before the previous is handled
    ```



=== "DIFFERENT_EVENTS_17"

    ```
	[Originator@6876 sub=Libs opID=4c3d8875-40-3303 sid=5290a04a user=testUser:DOMAIN_START
    pxd-extension-UUIDTEST] ConfigFileLocker: /tmp/.simsOpLock.lock.LOCK: stale lock detected for PID 5318306: No such process
    ```



=== "DIFFERENT_EVENTS_18"

    ```
	[Originator@6876 sub=Libs opID=4c3d8875-40-3303 sid=5290a04a user=testUser:DOMAIN_START
    pxd-extension-UUIDTEST] Util: ForkExec(/etc/init.d/testDomain ++group=host/vim/tmp start) 5318781
    ```



=== "DIFFERENT_EVENTS_19"

    ```
	[Originator@6876 sub=Libs opID=ef773316] PluginLdr_Load: Loaded plugin 'libvmiof-disk-spm.so' from '/usr/lib64/vmware/plugin/libvmiof-disk-spm.so'
    ```



=== "DIFFERENT_EVENTS_2"

    ```
	[Originator@6876 sub=Default] Processing defaultMappingFile: /etc/vmware/rhttpproxy/endpoints.conf
    ```



=== "DIFFERENT_EVENTS_20"

    ```
	[Originator@6876 sub=Libs opID=ef773c99 sid=52376b0f user=root] PluginLdr_Load: Loaded plugin 'libvmiof-disk-vmwarevmcrypt.so' from '/usr/lib64/vmware/plugin/libvmiof-disk-vmwarevmcrypt.so'
    ```



=== "DIFFERENT_EVENTS_21"

    ```
	[Originator@6876 sub=Libs opID=ef7739e6 sid=5290a04a user=testUser] SlowRefresh: path /vmfs/volumes/volume-uuid total blocks 2397665492992 used blocks 1828253073408forceRefresh = 0
    ```



=== "DIFFERENT_EVENTS_22"

    ```
	[Originator@6876 sub=PluginLauncher] Launching binary: /usr/lib/vmware/healthd/plugins/bin/core_services.py ++group=healthd-plugins,mem=40 -u http://localhost:9996 --loglevel=error
    ```



=== "DIFFERENT_EVENTS_23"

    ```
	[Originator@6876 sub=PluginLauncher] Launching binary: /usr/lib/vmware/healthd/plugins/bin/vpxa.py ++group=healthd-plugins,mem=40 -u http://localhost:9996 --loglevel=error
    ```



=== "DIFFERENT_EVENTS_24"

    ```
	[Originator@6876 sub=Proxy Req 00015] Resolved endpoint : [N7Vmacore4Http16LocalServiceSpecE:0x000000cb75954ca0] _serverNamespace = /sdk action = Redirect authenticationParams =  _port = 8307
    ```



=== "DIFFERENT_EVENTS_25"

    ```
	[Originator@6876 sub=RhttpProxy] [N7Vmacore4Http15LocalTunnelSpecE:0x000000cb7594f880] _serverNamespace = /vsanperf action = Allow authenticationParams =  _port = 9095
    ```



=== "DIFFERENT_EVENTS_26"

    ```
	[Originator@6876 sub=Proxy Req 99717] Connection to localhost:9096 (/vsan) failed with error N7Vmacore15SystemExceptionE(Connection refused: The remote service is not running, OR is overloaded, OR a firewall is rejecting connections.)
    ```



=== "DIFFERENT_EVENTS_27"

    ```
	[Originator@6876 sub=Proxy Req 99721] New proxy client <io_obj p:0x000000cbb90037e8, h:22, <TCP '127.0.0.1 : 80'>, <TCP '127.0.0.1 : 44604'>>
    ```



=== "DIFFERENT_EVENTS_28"

    ```
	[Originator@6876 sub=Proxy Req 99723] Connected to localhost:8307 (/sdk) over <io_obj p:0x000000cbb8f53518, h:32, <TCP '127.0.0.1 : 57721'>, <TCP '127.0.0.1 : 8307'>>
    ```



=== "DIFFERENT_EVENTS_29"

    ```
	[Originator@6876 sub=Snmpsvc] GenerateFullReport: report file /tmp/.vm-report.xml generated, size 268 bytes.
    ```



=== "DIFFERENT_EVENTS_3"

    ```
	[Originator@6876 sub=HealthdHandler] Report Path: /var/lib/vmware/osdata/healthd/hostd-health
    ```



=== "DIFFERENT_EVENTS_30"

    ```
	[Originator@6876 sub=Snmpsvc] PublishReport: file /tmp/.vm-report.xml published as /tmp/vm-report.xml
    ```



=== "DIFFERENT_EVENTS_31"

    ```
	[Originator@6876 sub=Solo.Vmomi opID=vsan-wfu-d05d-36dd sid=52f14cc5 user=testUser] Activation finished; <<sessionUUID, <TCP '127.0.0.1 : 8307'>, <TCP '127.0.0.1 : 19402'>>, session[sessionUUID]525bd4db-73e1-6e31-7086-11c083988ebf, vmodl.query.PropertyCollector.waitForUpdatesEx>
    ```



=== "DIFFERENT_EVENTS_32"

    ```
	[Originator@6876 sub=SysCommandPosix opID=e7c4d063-332d sid=52a29a7d user=testUser:testDomain] ForkExec(/bin/sh) 5318859
    ```



=== "DIFFERENT_EVENTS_33"

    ```
	[Originator@6876 sub=VMXStatsProvider(000000d75ee69d30)] AddVM: VM '17' already registered
    ```



=== "DIFFERENT_EVENTS_34"

    ```
	[Originator@6876 sub=Vimsvc.HaSessionManager opID=ef773308 sid=52f14cc5] Accepted password for user testUser from 127.0.0.1 - session=sessionUUID
    ```



=== "DIFFERENT_EVENTS_35"

    ```
	[Originator@6876 sub=Vimsvc.HaSessionManager opID=ef773c95 sid=52376b0f] Accepted password for user root from 3.4.5.6 - session=52376b0f-4a63-82ee-6a40-4bb3e8fa4ea5
    ```



=== "DIFFERENT_EVENTS_36"

    ```
	[Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/volume-uuid/37MD-PORTAIL-B/37MD-PORTAIL-B.vmx opID=SWI-27d70fb0-67-3714 sid=5290a04a user=testUser:<no user>] File - failed to get objectId, '/vmfs/volumes/volume-uuid/37MD-PORTAIL-B/37MD-PORTAIL-B.vmx': Operation not supported (11)
    ```



=== "DIFFERENT_EVENTS_37"

    ```
	[vSAN@6876 sub=PyBackedMO opID=Main] Intercepting vim.host.VsanSystemEx.vmMonitorWatchObjects on 'vsanSystemEx'
    ```



=== "DIFFERENT_EVENTS_4"

    ```
	Could not get state for NFS volume 1.2.3.4-ActiveBackupforBusiness
    ```



=== "DIFFERENT_EVENTS_5"

    ```
	Terminating watchdog process with PID 5318810
    ```



=== "DIFFERENT_EVENTS_6"

    ```
	[Originator@6876 sub=Default] New/Updated endpoint added: /api
    ```



=== "DIFFERENT_EVENTS_7"

    ```
	[Originator@6876 sub=RhttpProxy] New/Updated endpoint added: /wsman
    ```



=== "DIFFERENT_EVENTS_8"

    ```
	[Originator@6876 sub=Hostsvc.NetworkProvider opID=ef77330f sid=52f14cc5 user=testUser:testDomain] SetIPv6Capability: IPv6 is enabled
    ```



=== "DIFFERENT_EVENTS_9"

    ```
	[Originator@6876 sub=Hostsvc.NetworkProvider opID=ef77330f sid=52f14cc5 user=testUser:testDomain] WOL capability for nic cannot be turned on.probable bug file against driver: ntg3
    ```



=== "NETWORK_HOSTNAME"

    ```
	 DHCPDISCOVER on vmk1 to 255.255.255.255 port 67 interval 1
    ```



=== "NETWORK_SOURCE"

    ```
	Connection from 1.2.3.4 port 33398
    ```



=== "PROCESS_1"

    ```
	info hostd[111111] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxui-1111-1111] Event 65352 : Cannot login root@1.2.3.4
    ```



=== "PROCESS_2"

    ```
	info hostd[111111] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxui-1111-1111] Event 111918 : Cannot login test@1.2.3.4
    ```



=== "PROCESS_BEGIN"

    ```
	info vpxa[2100523] [Originator@6876 sub=vpxLro opID=PollQuickStatsLoop-37dc5435-21] [VpxLRO] -- BEGIN lro-437646 -- vpxa -- vpxapi.VpxaService.fetchQuickStats -- 12345678-abcd-ef90-1234-abcdef123456
    ```



=== "PROCESS_CLOSED_STREAM"

    ```
	verbose rhttpproxy[2099517] [Originator@6876 sub=Proxy Req 56374] The client closed the stream, not unexpectedly.
    ```



=== "PROCESS_CMD"

    ```
	Executing 'vsanmgmtd -s -c /etc/vmware/vsan/vsanmgmt-config.xml'
    ```



=== "PROCESS_CMD_user"

    ```
	USER root pid 9919303 cmd /bin/hostd-probe.sh ++group=host/vim/vmvisor/hostd-probe/stats/sh
    ```



=== "PROCESS_CMD_user_1"

    ```
	User 'root' running command 'USER=vpxuser python ++group=host/vim/vmvisor/ntnx /get_one_time_password.py'
    ```



=== "PROCESS_INFO"

    ```
	info hostd[2100582] [Originator@6876 sub=Libs opID=sps-Main-845080-412-fa-fc-87e0 user=vpxuser:USER.LOCAL\vpxd-extension-12345678-abcd-ef90-1234-abcdef123456] (403)
    ```



=== "PROCESS_LOG_LAUNCHING"

    ```
	healthd: info healthd[2100572] [Originator@6876 sub=PluginLauncher] Launching binary: /usr/lib/vmware/healthd/plugins/bin/ssdStorage.py ++group=healthd-plugins,mem=40 -u http://localhost:9996
    ```



=== "PROCESS_WARNING"

    ```
	warning hostd[2102845] [Originator@6876 sub=VigorStatsProvider(000000609e3d09a0).GuestStats(28)] SetVigorNotificationTime: Not connected
    ```



=== "SSHD_ERROR_INVALID_USER"

    ```
	sshd[2102293]: Invalid user administrator from 1.2.3.4 port 41100
    ```



=== "SSHD_MESSAGE_DISCONNECTED"

    ```
	sshd[2102280]: Disconnected from authenticating user root 1.2.3.4 port 21289 [preauth]
    ```



=== "VARIOUS_DEVICE_OUTCOME_REASON"

    ```
	error fdm[7599783] [Originator@6876 sub=Cluster opID=SWI-3cc8cdca] stat(/vmfs/volumes/aaaaaaaa-bbbbbbbb/.vSphere-HA/FDM-ffffffff-1111-4444-5555-666666666666-7-9999999-lnpvcr02) failed with Permission denied
    ```



=== "VARIOUS_FILE_ACTION"

    ```
	Unlocked esx.conf
    ```



=== "VARIOUS_FILE_ACTION_1"

    ```
	 Event [1201736] [2-3]  (fileName = "ds:///vmfs/volumes/63985d53-c3598817-6688-5c6f69e18ad0/HDD01-835/HDD01-835.vmdk", datastore = 'vim.Datastore:d6543eda-9347-4b38-b803-6f5048248ea8:datastore-2809', backingObjectId = "", diskMode = "independent_nonpersistent", split = <unset>, writeThrough = <unset>, thinProvisioned = false, eagerlyScrub = false, uuid = "6000C299-dd5c-07cb-b868-3600b53d2781", contentId = "5c1d0d8547e8b15283e287f5cb18ef5e", changeId = <unset>, parent = null, deltaDiskFormat = <unset>, digestEnabled = false, deltaGrainSize = <unset>, deltaDiskFormatVariant = <unset>, sharing = <unset>, keyId = null, cryptoIntegrityProtectionType = <unset>), deltaDiskFormat = "seSparseFormat", digestEnabled = false, deltaGrainSize = 4, deltaDiskFormatVariant = <unset>, sharing = "sharingNone", keyId = null, cryptoIntegrityProtectionType = <unset>), connectable = null, slotInfo = null, controllerKey = 1000, unitNumber = 3, numaNode = <unset>, capacityInKB = 104857600, capacityInBytes = 107374182400, shar
    ```



=== "VARIOUS_FILE_NAME_ACTION"

    ```
	 Event [1201186] [2-3] 18", changeId = "52 a6 e5 88 a3 05 f0 85-c0 ff 83 ec 24 78 73 49/13", parent = (fileName = "ds:///vmfs/volumes/63985d53-c3598817-6688-5c6f69e18ad0/HDD01-839/HDD01-839.vmdk", datastore = 'vim.Datastore:d6543eda-9347-4b38-b803-6f5048248ea8:datastore-2809', backingObjectId = "", diskMode = "independent_nonpersistent", split = <unset>, writeThrough = <unset>, thinProvisioned = false, eagerlyScrub = false, uuid = "6000C295-97b3-0e92-7f53-a3a8cc8386f3", contentId = "05e464ba43b8adc7714684dc68da836a", changeId = <unset>, parent = null, deltaDiskFormat = <unset>, digestEnabled = false, deltaGrainSize = <unset>, deltaDiskFormatVariant = <unset>, sharing = <unset>, keyId = null, cryptoIntegrityProtectionType = <unset>), deltaDiskFormat = "seSparseFormat", digestEnabled = false, deltaGrainSize = 4, deltaDiskFormatVariant = <unset>, sharing = "sharingNone", keyId = null, cryptoIntegrityProtectionType = <unset>), connectable = null, slotInfo = null, controllerKey = 1000, unitNumber = 6, numa
    ```



=== "VARIOUS_KEY_ACTION"

    ```
	Using key ID  527683eb-be00-ae48-b12d-06e5cffe4c7e to encrypt
    ```



=== "VARIOUS_REASON_1"

    ```
	  [iscsiCorrelator] 3087813295957us: [vob.iscsi.connection.stopped] iScsi connection 0 stopped for vmhba64:C0:T3
    ```



=== "VARIOUS_REASON_10"

    ```
	  info fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1b24a1a7] Unset _accessible for datastore (/vmfs/volumes/aaaaaaaa-bbbbbbbb)
    ```



=== "VARIOUS_REASON_11"

    ```
	cpu7:2097868)WARNING: ql_fcce:vmhba65:FipVlanTimeoutWork:249: FAP VLAN Max Retries reached, cur vlan and pri: 1002
    ```



=== "VARIOUS_REASON_12"

    ```
	error hostd[5806021] [Originator@6876 sub=Default] [LikewiseGetDomainJoinInfo:354] QueryInformation(): ERROR_FILE_NOT_FOUND (2/0):
    ```



=== "VARIOUS_REASON_2"

    ```
	 connection 4:0 (iqn.2010-06.com.nutanix:iscsi-dump-c086c177-a1f4-48be-a3b2-b5f2b6517fa6 if=default addr=1.2.3.4:3260 (TPGT:1 ISID:0x1)  (T3 C0)) has recovered (2 attempts)
    ```



=== "VARIOUS_REASON_3"

    ```
	 info hostd[2099655] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=233816e0 user=vpxuser] Event 974626 : User vpxuser@10.79.50.22 logged out (login time: Tuesday, 18 April, 2023 07:14:36 AM, number of API invocations: 3, user agent: pyvmomi)
    ```



=== "VARIOUS_REASON_4"

    ```
	 info rhttpproxy[2102807] [Originator@6876 sub=IO.Connection] Failed to shutdown socket; <io_obj p:0x000000f7c12bd0a8, h:23, <TCP '5.6.7.8 : 443'>, <TCP '1.2.3.4 : 39664'>>, e: 104(shutdown: Connection reset by peer)
    ```



=== "VARIOUS_REASON_5"

    ```
	  verbose rhttpproxy[2099165] [Originator@6876 sub=Proxy Req 06028] Connected to localhost:8307 (/sdk) over <io_obj p:0x000000f7c12be288, h:24, <TCP '127.0.0.1 : 29013'>, <TCP '127.0.0.1 : 8307'>>
    ```



=== "VARIOUS_REASON_6"

    ```
	  error kmxa[2098475] [Originator@6876 sub=Libs opID=InitCache-52a74d0e-554c-1fc3-1b1f-bd3c439fd0a3-0] Trust Authority Components not configured.
    ```



=== "VARIOUS_REASON_7"

    ```
	 verbose fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1361339f] Healthstatus of VM /vmfs/volumes/0ced57f7-f5da65c8/ntpnim02/ntpnim02.vmx on live hostId host-103 : true
    ```



=== "VARIOUS_REASON_8"

    ```
	 info hostd[2099655] [Originator@6876 sub=Libs opID=2338d373 user=vpxuser] NetstackInstanceImpl: congestion control algorithm: newreno
    ```



=== "VARIOUS_REASON_9"

    ```
	info fdm[7599763] [Originator@6876 sub=Invt opID=SWI-1b24a1a7] Unset _accessible for datastore (/vmfs/volumes/aaaaaaaa-bbbbbbbb)
    ```



=== "VARIOUS_SERIAL_NUMBER_1"

    ```
	 QuerySerialNumber --- real serial number is 1111222233334444
    ```



=== "VARIOUS_SERIAL_NUMBER_2"

    ```
	 get_serial_num_of_SATA_SAS_disk---serial num is 1111222233334444
    ```



